# Site settings
title: Neil Agarwal
email: regalstreak@gmail.com
url: https://regalstreak.me
enforce_ssl: regalstreak.me
description: "Welcome to Neil Agarwal, a.k.a. regalstreak's den."
skills: "Neophile - Android Developer - EDM Lover"
meta_author: Agarwal Neil

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: disqus

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: regalstreak

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Neil Agarwal
  #location: Location
  social: Around the Web
  #credits: More Stuff

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - name: BasketBuild
    title: shopping-basket
    url: https://basketbuild.com/devs/regalstreak
  - name: XDA
    title: mobile
    url: http://forum.xda-developers.com/member.php?u=5325978
  - name: GitHub
    title: github
    url: https://github.com/regalstreak
  - name: Gitlab
    title: gitlab
    url: https://gitlab.com/regalstreak
  - name: AndroidFileHost
    title: android
    url: https://www.androidfilehost.com/?w=profile&uid=23501681358561822
  - name: YouTube
    title: youtube
    url: https://www.youtube.com/user/TheRegalstreak
  - name: Twitter
    title: twitter
    url: https://twitter.com/regalstreak
  - name: Facebook
    title: facebook
    url: https://www.facebook.com/regalstreak
  - name: Google+
    title: google-plus
    url: https://plus.google.com/u/0/116835007029095043966
  - name: Instagram
    title: instagram
    url: https://www.instagram.com/regalstreak_/

# Postal address (add as many lines as necessary)
#address:
#  - line: Mumbai 400709
#  - line: Maharashtra, India

# Credits content
#credits: 'Look into _includes/footer.html. This has been disabled.'

# Build settings
markdown: kramdown
permalink: pretty
